# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=0)),
                ('customer', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=200)),
                ('photos', models.FileField(upload_to=None)),
                ('contact', models.IntegerField(default=0)),
            ],
        ),
    ]
