# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50)),
                ('image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('reviews', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(default=1)),
            ],
        ),
    ]
