# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DhoondhLega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
